test:
  dialect: mysql
  datasource: root:root@tcp(127.0.0.1:3308)/kit_enrollment_helper_test?parseTime=true
  dir: migrations
  table: test_migrations

development:
  dialect: mysql
  datasource: root:root@tcp(127.0.0.1:3308)/kit_enrollment_helper?parseTime=true
  dir: migrations
  table: gorp_migrations
