version: "3.9"
services:
  db:
    build: ./docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    networks:
      - kit-enrollment-helper-net

networks:
  kit-enrollment-helper-net:
    name: kit-enrollment-helper-net
