version: "3.9"
services:
  db:
    build: ./docker/mysql
    container_name: keh-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kit_enrollment_helper
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3308:3306"
    networks:
      - keh-net

networks:
  keh-net:
    name: keh-net
