name: Generate DB Docs

on:
  push:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Set up tools
        run: make init/tools

      - name: Set up DB
        run: make database/init

      - name: Run tbls
        run: tbls doc
